---
# tasks file for dbserver
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: ensure mysql is configured to bind to the specified address and port
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: "bind-address"
    value: "0.0.0.0"
  notify:
    - restart mysql server

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL,GRANT
    host='%'
